---
title: "Final Report"
author: "Amy Leung and Maximilian Pschorr"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    fig_caption: yes
    number_sections: yes
    toc_depth: 3
    toc: yes
vignette: >
  %\VignetteIndexEntry{Final Report}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

# Introduction

####################### PLEASE EDIT AS YOU SEE FIT--I JUST JOTTED THOUGHTS DOWN QUICKLY ##################
As tropical storms and natural disasters occur more frequently and more intensely with climate change, it is imperative for communities to build greater resiliency in response to increasingly volatile natural hazards. Mitigation strategies and community preparedness plans are meant to lessen the loss of life and property, but there is not a one-size-fits-all approach to community capacity building. Vulnerability may not be uniformly or equally distributed across any one particular area, and different communities may have drastically different types of needs. 

In an effort to quantify the myriad of socioeconomic factors contributing to vulnerability, Cutter et al. (2003) [(http://onlinelibrary.wiley.com/doi/10.1111/1540-6237.8402002/abstract)] developed a national Social Vulnerability Index (SoVI) that served as the foundation for the Social Vulnerability Index (SVI) developed by the US Department of Homeland Security (2011), in conjunction with the Centers for Disease Control (CDC) and the Agency for Toxic Substances and Disease Registry (ATSDR). This SVI currently acts as the authoritative national social vulnerability index and is used by emergency and disaster management professionals in pre- and post-disaster activities. 

The SVI is comprised of four thematic domains: Socioeconomic Status, Housing Composition and Disability, Minority Status and Language, and Housing and Transportation. Spread across each of these domains are 15 aggregate variables calculated from 2010 – 2014 American Community Survey (ACS) 5-year estimates and flagged based on 90th percentile values (i.e. the top 10% most vulnerable values). 

# Methods

PostgreSQL/PostGIS - necessary for storing large SVI dataset
Shiny - develop interactive web application for users to upload/download SVI for their AOIs
Packages - (subsection) discuss importance of each package used, and the functionality used in each

# Results

Fully functional Shiny web app
Four functions to style and create interactive dashboard, boxplot, calculate SVI, and style leaflet map
Downloadable SVI results

# Discussion

Limitations - many package dependencies (are these absolutely necessary?), users must currently have a postgreSQL/PostGIS db set up exactly like ours for the app to run, rendering large polys takes a long(er) time to run (re: see sandy path shapefile)
Improvements - add option for user to draw extent polygon as input, add highlight to poly to show which is displayed in dashboard, figure out a workaround to remove dependency on setting up a db exactly like ours

#### Note for Dr. Lyndon Estes and Zhiwen Zhu, regarding documentation of the division of labor: where appropriate, division of labor on different tasks is denoted in the following fashion: Amy = `DOL:A`, Max = `DOL:M`, Both Amy and Max = `DOL:B`
